docusaurus/docs/tutorial-extras/node-provider-faq.md

1. This is the first version of the node provider FAQ. 
2. I've added around 20 answers to the questions I had.
3. We can complete the remaining questions afterward, everyone is welcome to contribute.

Add node provider FAQ

---

docusaurus/src/components/HomepageFeatures/index.js
docusaurus/src/css/custom.css

- https://color.adobe.com/search?q=pastel

Change color palette to one that's inspired by Anderson's Asteroid City

---

docusaurus/docs/getting-started/install-dfx.md

Add document about installing dfx.

Add document for installing dfx.

---

.github/workflows/deploy-staging.yml

Add GitHub action to deploy to the staging canister while pushing to the main branch.

Add GitHub action.

---

docusaurus/docs/getting-started/ic-glossary.md

Use `{#}` to customize the anchors.
**_Notice_**:  Github markdown engine doesn't support `{#}`, but the markdown engine we use in `docusauras` does support it.

Change glossary anchor

---

docusaurus/docs/apps-guide/openchat/guide.md

add openchat invitation link and fix format issue.

add openchat invitation link and fix format issue.

---

docusaurus/docs/ic-web3/submit-nns-proposal.md

add submit nns proposal guide

---

docusaurus/docs/ecosystem-guide/1-node-provider-faq/index.md

Update the node provide faq to include validation script and network bandwidth.

Update the node provide faq to include two more questions.

---

.github/workflows/deploy-staging.yml
docusaurus/docs/about/4-github-action/index.md

Support manual trigger for staging deployment.

Staging deployment trigger

---

docusaurus/docs/getting-started/6-deploy-dfx/index.md
docusaurus/docs/getting-started/6-use-dfx/index.md

This pr mainly adds documents for `dfx` usage about `identity`, `ledger`, `wallet`, and `canister`.

Add document for using dfx.

---

docusaurus/docs/getting-started/3-get-cycles/index.md

获取cycles的方式有些改动，发出的指令改为`/request`

update the discord command to request cycles

---

docusaurus/docs/getting-started/6-use-dfx/index.md

Add dfx document for
1. development, including start, stop, new, build, deploy
2. others, including help, upgrade, ping.

Add more dfx document

---

docusaurus/docs/getting-started/6-use-dfx/index.md

Add document for `dfx ledger fabricate-cycles`.

Add dfx v3

---

docusaurus/docs/ecosystem-guide/3-co-marketing/index.md

Update pr request link.

---

docusaurus/docs/apps-guide/27-cbindex/index.md

Enable CBIndex app guide, along with some minor changes.

Enable CBIndex app guide, along with some minor changes.

---

docusaurus/docs/getting-started/3-get-cycles/index.md

1. Add introductions to cycles and cycles wallet
2. Add instructions about how to convert ICP tokens to cycles
3. Add instructions about how to top-up canisters

Update `get cycles` document

---

docusaurus/docs/getting-started/get-cycles/index.md

1. Add a basic introduction about cycles ledger.
2. Also adjust the page layout for the cycles page.

Add document for cycles ledger.

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

Fixed the GitHub actions by updating the URL of the installing script.

Update the URL of the installing script.

---

docusaurus/docs/getting-started/install-dfx/index.md

1. Update the document to reflect the recent changes about installing dfx.
2. Add a simple document about how to use `dfxvm`.
3. Use tabs for Mac/Linux and Windows.
4. Add English anchors.

Update the document about installing dfx.

---

docusaurus/docs/getting-started/use-dfx/index.md

fix url bug

---

CHANGELOG.md
docusaurus/docs/getting-started/get-cycles/index.md

Update get cycles page by removing getting free cycles from cycles faucet.

Update get cycles page by removing getting free cycles from cycles faucet.
